# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='tb_areas',
        ),
    ]
